### ISSUE TITLE
Better maintenance by separating golden verification and runtime benchmarking

### ISSUE THREAD

**Issue by yungyuc** [eesss34690/Cache_Optimization#1]
In your automatic testing, the code for timing:

https://github.com/eesss34690/Cache_Optimization/blob/98ec232ff38b1a4e488d426b36f35bf645ca8fcf/test_fft.py#L21

and that for verifying the golden:

https://github.com/eesss34690/Cache_Optimization/blob/98ec232ff38b1a4e488d426b36f35bf645ca8fcf/test_fft.py#L54

are mixed in the same testing function.  It may give you a little bit difficulty in future maintenance.

In addition, properly organized testing code may improve your productivity.  The mix of the two types of test makes it harder to use simple CI like Github Action, while adding CI will definitely help your productivity.

You can probably evaluate the pros and cons.  It's my 2 cents.

**Comment by eesss34690** [comment]
Ok, I simply try this for initial testing to confirm the correctness.
In the newer version I will separate the two tests and add CI test

**Comment by yungyuc** [comment]
Sounds like a plan.
